version: "3.1"
services:
  db:
    image: mariadb:10.4
    container_name: mariadb
    restart: unless-stopped
    tty: true
    volumes:
      - database:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=api-laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sft6033
      - MYSQL_ROOT_PASSWORD=sft6033
    ports:
      - "8083:3306"
    networks:
      - myNetwork

  server:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    working_dir: /application
    volumes:
      - ./src:/application
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - db
    networks:
      - myNetwork

  app:
    build: .
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /application
    volumes:
      - ./src:/application
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge

volumes:
  database:
    driver: local